from pyspark.sql.types import StructType, StructField, StringType, IntegerType

schemas = {
    "obic_プロジェクトリスト": StructType([
    StructField("営業担当事業所コード", StringType(), True),
    StructField("営業担当事業所略名", StringType(), True),
    StructField("営業担当部署コード", StringType(), True),
    StructField("営業担当部署略名", StringType(), True),
    StructField("プロジェクトNO", StringType(), True),
    StructField("プロジェクト区分", StringType(), True),
    StructField("プロジェクト略名", StringType(), True),
    StructField("プロジェクト名", StringType(), True),
    StructField("予定期間_開始", StringType(), True),
    StructField("予定期間_終了", StringType(), True),
    StructField("登録日", StringType(), True),
    StructField("完了日", StringType(), True),
    StructField("営業担当者コード", StringType(), True),
    StructField("営業担当者名", StringType(), True),
    StructField("得意先コード", StringType(), True),
    StructField("得意先略名", StringType(), True),
    StructField("請求先コード", StringType(), True),
    StructField("請求先略名", StringType(), True),
    StructField("先方注文番号", StringType(), True),
    StructField("プロジェクトコメント1", StringType(), True),
    StructField("プロジェクトコメント2", StringType(), True),
    StructField("得意先名", StringType(), True),
    StructField("得意先郵便番号1", StringType(), True),
    StructField("得意先郵便番号2", StringType(), True),
    StructField("得意先住所1", StringType(), True),
    StructField("得意先住所2", StringType(), True),
    StructField("得意先住所3", StringType(), True),
    StructField("得意先部署名", StringType(), True),
    StructField("得意先役職名", StringType(), True),
    StructField("得意先担当者名", StringType(), True),
    StructField("得意先電話番号1", StringType(), True),
    StructField("得意先電話番号2", StringType(), True),
    StructField("得意先電話番号3", StringType(), True),
    StructField("得意先FAX番号1", StringType(), True),
    StructField("得意先FAX番号2", StringType(), True),
    StructField("得意先FAX番号3", StringType(), True),
    StructField("得意先メールアドレス", StringType(), True),
    StructField("請求先名", StringType(), True),
    StructField("請求先郵便番号1", StringType(), True),
    StructField("請求先郵便番号2", StringType(), True),
    StructField("請求先住所1", StringType(), True),
    StructField("請求先住所2", StringType(), True),
    StructField("請求先住所3", StringType(), True),
    StructField("請求先部署名", StringType(), True),
    StructField("請求先役職名", StringType(), True),
    StructField("請求先担当者名", StringType(), True),
    StructField("請求先電話番号1", StringType(), True),
    StructField("請求先電話番号2", StringType(), True),
    StructField("請求先電話番号3", StringType(), True),
    StructField("請求先FAX番号1", StringType(), True),
    StructField("請求先FAX番号2", StringType(), True),
    StructField("請求先FAX番号3", StringType(), True),
    StructField("請求先メールアドレス", StringType(), True),
    StructField("処理ユーザID", StringType(), True),
    StructField("処理日時", StringType(), True),
    StructField("取込番号", StringType(), True),
    StructField("取込日時", StringType(), True),
    StructField("承認状況", StringType(), True),
    StructField("売上基準設定単位区分", StringType(), True),
    StructField("売上基準", StringType(), True),
    StructField("会社NO", StringType(), True),
    StructField("会社略名", StringType(), True),
    StructField("出力ユーザID", StringType(), True)
]),
    "table2": StructType([
        StructField("列A", StringType(), True),
        StructField("列B", IntegerType(), True)
    ]),
    "table3": StructType([
        StructField("カラム1", StringType(), True),
        StructField("カラム2", StringType(), True)
    ])
}
